# Generated by Django 4.2.5 on 2023-10-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodigoCreativoApp', '0002_blog_subtitle_alter_blog_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
