# Generated by Django 4.2.5 on 2023-10-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodigoCreativoApp', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='min_img_url',
        ),
    ]
