# Generated by Django 4.2.5 on 2023-10-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodigoCreativoApp', '0009_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='post-image'),
        ),
    ]
