# Generated by Django 4.2.5 on 2023-10-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodigoCreativoApp', '0011_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(null=True, upload_to='post-image'),
        ),
    ]
