# Generated by Django 4.2.5 on 2023-10-07 18:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodigoCreativoApp', '0012_alter_blog_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(default=None, upload_to='post-image'),
        ),
    ]
