# Generated by Django 4.2.5 on 2023-10-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodigoCreativoApp', '0014_mensajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(default=None, upload_to='post_image'),
        ),
    ]
