# Generated by Django 4.2.5 on 2023-10-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodigoCreativoApp', '0016_mensajes_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
