# Generated by Django 4.2.5 on 2023-10-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodigoCreativoApp', '0017_mensajes_spam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='leido',
        ),
        migrations.RemoveField(
            model_name='mensajes',
            name='spam',
        ),
        migrations.RemoveField(
            model_name='mensajes',
            name='visible',
        ),
    ]
